services:
  database:
    image: postgres:13
    ports: [5433:5432]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tts
      POSTGRES_USER: tts
      POSTGRES_PASSWORD: tts_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tts -d tts"]
      interval: 5s
      timeout: 5s
      retries: 5

  # XTTS service now runs natively via conda - see start-xtts.sh script

volumes:
  postgres_data: